export const BASE_URL = "https://thecartzilla.shop"
export const ADMIN_BASE_URL = "https://thecartzilla.shop/api/admin"
export const USER_BASE_URL = "https://thecartzilla.shop/api/user"
export const EMPLOYER_BASE_URL = "https://thecartzilla.shop/api/employer"
export const CHAT_BASE_URL = "https://thecartzilla.shop/api/chats"