export const BASE_URL = "http://localhost:8080"
export const ADMIN_BASE_URL = "http://localhost:8080/api/admin"
export const USER_BASE_URL = "http://localhost:8080/api/user"
export const EMPLOYER_BASE_URL = "http://localhost:8080/api/employer"
export const CHAT_BASE_URL = "http://localhost:8080/api/chats"